web/board/urls.py
from django.urls import path
from . import views

from .views import (AccidentCreateView, AccidentListView, AccidentDetailView
                    ,AccidentUpdateView,AccidentDeleteView
                    , SafetyListView, SafetyCreateView, SafetyDetailView
                    , SafetyDeleteView, SafetyUpdateView, LogView, FieldlogView, FieldlogDetailView
                    , FieldlogDeleteView, FieldlogUpdateView, PreferencesView, EmployeeView
                    , EmployeeUpdateView, EmployeeDeleteView, GroupView, GroupDeleteView, DashboardView)

app_name = "board"

urlpatterns = [
    path('login/', views.Login, name="login"),
    path('logout/', views.Logout, name="logout"),
    path('signup/', views.Signup, name="signup"),
    path('log/', LogView.as_view(), name='log'),
    path('dashboard/', DashboardView.as_view(), name='dashboard'),
    path('dashboard/<int:pk>/', DashboardView.as_view(), name='dashboard_detail'),
    path('accident_write/', AccidentCreateView.as_view(), name='accident_write'),
    path('accident_list/', AccidentListView.as_view(), name='accident_list'),
    path('accident_detail/<int:pk>/', AccidentDetailView.as_view(), name='accident_detail'),
    path('accident_update/<int:pk>/', AccidentUpdateView.as_view(), name='accident_update'),
    path('accident_delete/<int:pk>/', AccidentDeleteView.as_view(), name="accident_delete"),
    path('safety_write/', SafetyCreateView.as_view(), name='safety_write'),
    path('safety_list/', SafetyListView.as_view(), name='safety_list'),
    path('safety_detail/<int:pk>/', SafetyDetailView.as_view(), name='safety_detail'),
    path('safety_update/<int:pk>/', SafetyUpdateView.as_view(), name='safety_update'),
    path('safety_delete/<int:pk>/', SafetyDeleteView.as_view(), name="safety_delete"),
    path('fieldlog_write/', FieldlogView.as_view(), name='fieldlog_write'),
    path('fieldlog_detail/<int:pk>/', FieldlogDetailView.as_view(), name='fieldlog_detail'),
    path('fieldlog_update/<int:pk>/', FieldlogUpdateView.as_view(), name='fieldlog_update'),
    path('fieldlog_delete/<int:pk>/', FieldlogDeleteView.as_view(), name='fieldlog_delete'),
    path('preferences/', PreferencesView.as_view(), name="preferences_list"),
    path('preferences/<int:pk>/', PreferencesView.as_view(), name="preferences_detail"),
    path('employee/', EmployeeView.as_view(), name="employee"),
    path('employee_detail/<int:pk>/', EmployeeView.as_view(), name='employee_detail'),
    path('employee_update/<int:pk>/', EmployeeUpdateView.as_view(), name="employee_update"),
    path('employee_delete/<int:pk>/', EmployeeDeleteView.as_view(), name='employee_delete'),
    path('groups/', GroupView.as_view(), name='groups'),
    path('groups_delete/<int:pk>', GroupDeleteView.as_view(), name='groups_delete'),
    # path('profile/', profile, name='profile'),
    path('apimap/', views.Apimap, name="apimap"),
]

web/web/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('board/', include("board.urls")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

web/templates/page.html
<html lang="ko-kr">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <!-- CSS only -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65" crossorigin="anonymous">
    <!-- JavaScript Bundle with Popper -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-kenU1KFdBIe4zVF0s0G1M5b4hcpxyD9F7jL+jjXkk+Q2h455rYXK/7HAuoJl+0I4" crossorigin="anonymous"></script>
    <title>작업자상황판</title>
</head>

<body>
{% load static %}
<link rel="stylesheet" href="{% static 'page.css' %}">

{% block title %}
{% endblock title %}
    <div id="grid">
        <nav class="nav flex-column">
            <a href="{% url 'board:dashboard'%}" class="nav-link">작업자상황판</a>
            <a href="{% url 'board:employee'%}" class="nav-link">직원등록</a>
            <a href="{% url 'board:groups'%}" class="nav-link">근무편성</a>
            <a href="{% url 'board:log'%}" class="nav-link">일일기록</a>
            <a href="{% url 'board:accident_list'%}" class="nav-link">사고보고</a>
            <a href="{% url 'board:safety_list'%}" class="nav-link">안전점검일지</a>
            <a href="{% url 'board:fieldlog_write'%}" class="nav-link">작업현장일지</a>
            <a href="{% url 'board:preferences_list'%}" class="nav-link">관리자 정보</a>
            <a href="{% url 'board:logout' %}" class="nav-link">로그아웃</a>
        </nav>
        <div>
        {% block content %}
        {% endblock content %}
        </div>
    </div>
</body>
</html>