web/board/urls.py
from django.urls import path
from . import views

from .views import (AccidentCreateView, AccidentListView, AccidentDetailView
                    ,AccidentUpdateView,AccidentDeleteView
                    , SafetyListView, SafetyCreateView, SafetyDetailView
                    , SafetyDeleteView, SafetyUpdateView, LogView, FieldlogView, FieldlogDetailView
                    , FieldlogDeleteView, FieldlogUpdateView, PreferencesView, EmployeeView
                    , EmployeeUpdateView, EmployeeDeleteView, GroupView, GroupDeleteView, DashboardView)

app_name = "board"

urlpatterns = [
    path('login/', views.Login, name="login"),
    path('logout/', views.Logout, name="logout"),
    path('signup/', views.Signup, name="signup"),
    path('log/', LogView.as_view(), name='log'),
    path('dashboard/', DashboardView.as_view(), name='dashboard'),
    path('dashboard/<int:pk>/', DashboardView.as_view(), name='dashboard_detail'),
    path('accident_write/', AccidentCreateView.as_view(), name='accident_write'),
    path('accident_list/', AccidentListView.as_view(), name='accident_list'),
    path('accident_detail/<int:pk>/', AccidentDetailView.as_view(), name='accident_detail'),
    path('accident_update/<int:pk>/', AccidentUpdateView.as_view(), name='accident_update'),
    path('accident_delete/<int:pk>/', AccidentDeleteView.as_view(), name="accident_delete"),
    path('safety_write/', SafetyCreateView.as_view(), name='safety_write'),
    path('safety_list/', SafetyListView.as_view(), name='safety_list'),
    path('safety_detail/<int:pk>/', SafetyDetailView.as_view(), name='safety_detail'),
    path('safety_update/<int:pk>/', SafetyUpdateView.as_view(), name='safety_update'),
    path('safety_delete/<int:pk>/', SafetyDeleteView.as_view(), name="safety_delete"),
    path('fieldlog_write/', FieldlogView.as_view(), name='fieldlog_write'),
    path('fieldlog_detail/<int:pk>/', FieldlogDetailView.as_view(), name='fieldlog_detail'),
    path('fieldlog_update/<int:pk>/', FieldlogUpdateView.as_view(), name='fieldlog_update'),
    path('fieldlog_delete/<int:pk>/', FieldlogDeleteView.as_view(), name='fieldlog_delete'),
    path('preferences/', PreferencesView.as_view(), name="preferences_list"),
    path('preferences/<int:pk>/', PreferencesView.as_view(), name="preferences_detail"),
    path('employee/', EmployeeView.as_view(), name="employee"),
    path('employee_detail/<int:pk>/', EmployeeView.as_view(), name='employee_detail'),
    path('employee_update/<int:pk>/', EmployeeUpdateView.as_view(), name="employee_update"),
    path('employee_delete/<int:pk>/', EmployeeDeleteView.as_view(), name='employee_delete'),
    path('groups/', GroupView.as_view(), name='groups'),
    path('groups_delete/<int:pk>', GroupDeleteView.as_view(), name='groups_delete'),
    # path('profile/', profile, name='profile'),
    path('apimap/', views.Apimap, name="apimap"),
]

web/web/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('board/', include("board.urls")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

web/board/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
from datetime import date
#Manage + User = 회원가입, 로그인
class Manage(AbstractUser):
    STATUS = {
        ('감독','감독'),
        ('관리자','관리자'),
        ('반장','반장'),
    }
    position = models.CharField(max_length=30, choices=STATUS, null=True)
    address = models.CharField(max_length=200)
    call = models.CharField(max_length=20)

#로그기록
class LogRecord(models.Model):
    date = models.DateTimeField(auto_now_add=True)
    action = models.CharField(max_length=50)
    user = models.ForeignKey(Manage, on_delete=models.SET_NULL, null=True)

    def __str__(self):
        return f"{self.date} - {self.action} - {self.user.username}"
    
#사고보고
class Accident(models.Model):
    STATUS = {
        ('사고발생','사고발생'),
        ('조치 중','조치 중'),
        ('조치완료','조치완료'),
    }
    ac_area = models.CharField(max_length=50)
    ac_status = models.CharField(max_length=30, choices=STATUS, null=True)
    img = models.ImageField()
    ac_cont = models.TextField(null=True)
    create_date = models.DateTimeField(auto_now_add=True)
    update_date = models.DateTimeField(auto_now=True)
    writer = models.ForeignKey(Manage, on_delete=models.CASCADE)   #python manage.py createsuperuser   Manage Table

#안전점검일지
class Safety(models.Model):
    STATUS = {
        ('양호','양호'),
        ('주의','주의'),
        ('심각','심각'),
    }
    scl_area = models.CharField(max_length=50) #제목
    scl_status = models.CharField(max_length=30, choices=STATUS, null=True) #안전상태
    img = models.ImageField() #이미지
    scl_cont = models.TextField(null=True) # 내용
    create_date = models.DateTimeField(auto_now_add=True)
    update_date = models.DateTimeField(auto_now=True)
    writer = models.ForeignKey(Manage, on_delete=models.CASCADE)   #작성자

#작업현장일지
class Fieldlog(models.Model):
    fl_area = models.CharField(max_length=100) #공사구역
    fl_status = models.CharField(max_length=100) #작업내역
    img = models.ImageField()
    fl_cont = models.TextField(null=True) #일지내용
    create_date = models.DateTimeField(auto_now_add=True)
    update_date = models.DateTimeField(auto_now=True)
    writer = models.ForeignKey(Manage, on_delete=models.CASCADE) # 로그인 작성자
# # cmp = models.CharField(max_length=100) #회사

#댓글
class Replay(models.Model):  
    contents = models.TextField()
    create_date= models.DateTimeField(auto_now_add=True)
    writer = models.ForeignKey(Manage, on_delete=models.CASCADE) # 로그인 작성자
    post = models.ForeignKey(Accident, on_delete=models.CASCADE, null=True)
    fieldlog = models.ForeignKey(Fieldlog, on_delete=models.CASCADE, null=True)
    safety = models.ForeignKey(Safety, on_delete=models.CASCADE, null=True)
    #연결될 참조키 테이블, 불러오는 건 그 데이터값만 HTML에

# zip_code=models.IntegerField()
#직원
class Employee(models.Model): #pk 자동 생성
    STATUS = {
        ('감독','감독'),
        ('관리자','관리자'),
        ('반장','반장'),
    }
    cmp = models.CharField(max_length=40)
    emp_name = models.CharField(max_length=20)
    position = models.CharField(max_length=30, choices=STATUS, null=True)
    work = models.CharField(max_length=20)
    emp_call = models.CharField(max_length=20)
    date_of_birth = models.DateField(blank=True, null=True)
    address=models.CharField(max_length=200) #상세주소
    img = models.ImageField() #증명사진
    work_area = models.CharField(max_length=100) #담당구역
    start_time = models.DateField(blank=True, null=True) #작업 시작일
    end_time = models.DateField(blank=True, null=True) #작업 끝나는일
    create_date = models.DateTimeField(auto_now_add=True) #생성일
    update_date = models.DateTimeField(auto_now=True) #수정일
    serial_num = models.CharField(max_length=100) #단말기 시리얼넘버

#근무편성
class Group(models.Model):
    employee1 = models.ForeignKey(Employee, on_delete=models.CASCADE, related_name='group_employee1')
    employee2 = models.ForeignKey(Employee, on_delete=models.CASCADE, related_name='group_employee2')
    pair = models.IntegerField(null=True)
    
#입력은 직원에서 받는다. 그러면 직원을 웨어러블에 연결한다. 그리고 일대일로 가야한다
#웨어러블
class Wearable(models.Model):
    SIGN={
        (0, '체결'),
        (1, '미체결'),
        (2, '불량체결'),
    }
    STATUS = {
    (0, '양호'),
    (1, '관심'),
    (2, '주의'),
    (3, '경계'),
    (4, '심각'),
    }
    # serial_num = models.OneToOneField(Employee, on_delete=models.CASCADE) #일대일
    hook = models.IntegerField(choices=SIGN, null=True) #안전고리
    altitude = models.FloatField() #고도
    battery = models.IntegerField(null=True)#배터리
    degree_safety = models.IntegerField(choices=STATUS, null=True) #안전도
    event = models.IntegerField(null=True)
    create_date = models.DateTimeField(auto_now_add=True)
    update_date = models.DateTimeField(auto_now=True)
    # safe_cap = models.CharField(max_length=20)
    # safe_wch = models.CharField(max_length=20)
    # safe_tag = models.CharField(max_length=20)

web/board/forms.py
from django import forms
from board.models import Accident, Replay, Safety
from django.contrib.auth.forms import UserCreationForm
from .models import (Manage, Accident, Replay, Safety,
                     Group, Fieldlog, Employee)
from django.forms import DateInput
from django.core.exceptions import ValidationError
#회원가입
class SignupForm(UserCreationForm):
    class Meta:
        model= Manage
        fields = ('first_name', 'last_name', 'position', 'email', 'username', 'password1', 'password2', 'address', 'call')

#사고보고
class PostForm(forms.ModelForm):
    class Meta:
        model = Accident
        fields =('ac_area', 'ac_status', 'img', 'ac_cont')
        exclude={'writer', }

#안전점검일지
class SafetyForm(forms.ModelForm):
    class Meta:
        model = Safety
        fields =('scl_area', 'scl_status', 'img', 'scl_cont')
        exclude={'writer', }

#작업현장일지
class FieldlogForm(forms.ModelForm):
    class Meta:
        model = Fieldlog
        fields =('fl_area', 'fl_status', 'img', 'fl_cont')
        exclude={'writer', }

#직원
class EmployeeForm(forms.ModelForm):
    class Meta:
        model = Employee
        fields = '__all__'
        widgets = {
            'start_time': DateInput(attrs={'type': 'date'}),
            'end_time': DateInput(attrs={'type': 'date'}),
            'date_of_birth': DateInput(attrs={'type': 'date'}),
        }
#댓글
class ReplayForm(forms.ModelForm):
    class Meta:
        model = Replay
        fields = ('contents', )
        exclude = ('writer', )

#근무편성
class GroupForm(forms.ModelForm):
    class Meta:
        model = Group
        fields = ['employee1', 'employee2']
# message = forms.CharField(widget = forms.Textarea)
# db_table = ''
# managed = True
# verbose_name = 'ModelName'
# verbose_name_plural = 'ModelNames'
# fields = ('contents', ) #__all__

web/board/templates/board/accident_form.html
{% extends 'page.html' %}

{% block title %}
<h1 id="title">사고보고</h1>
{% endblock title %}


{% block content %}
    <!-- Your dashboard content goes here -->
{{user.username}}님 환영합니다.
<form action="" method="POST" enctype="multipart/form-data">
{% csrf_token %}
{{ form.as_p }}
<input class="btn btn-primary" type="submit" value="등록">
</form>
{% endblock %}

web/board/templates/board/accident_list.html
<html lang="ko-kr">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Elsaf</title>
</head>
<body>
{% extends 'page.html' %}
{% load static %}
<link rel="stylesheet" href="{% static 'list.css' %}">

{% block title %}
<h1 id="title">사고보고</h1>
{% endblock title %}

{% block content %}
<nav class="navbar bg-light">
    <div class="container-fluid">
        <div class="solt-1">
            <label class="blockquote" for="mgr_pw">총 사건{{total}}건   </label>
            <label class="lead" for="mgr_pw">   사고현황{{count1}}건  </label>
            <label class="lead" for="mgr_pw">   조치현황{{count2}}건</label>
        </div>

      <form class="d-flex" role="search">
        <input class="form-control me-2" type="search" placeholder="사고처리자 입력" aria-label="사고처리자">
        <button class="btn btn-outline-success" type="submit">검색</button>
      </form>
    </div>

</nav>
<div id="output">
    <table class="table table-hover" id="myTable" border="1" cellspacing="0" summary="사고보고 목록">
    <colgroup>
        <col width = "200">
        <col width = "200">
        <col width = "200">
        <col width = "80">
        <col width = "50">
    </colgroup>
    <thead>
        <th>생성일</th>
        <th>수정일</th>
        <th>사고구역</th>
        <th>조치상테</th>
        <th>사고처리자</th>
    </thead>
    {% for accident in accident_list  %}
    <tr class="link-dark" onclick="redirectToAccidentDetail('{{accident.id}}')">
    <td>{{accident.create_date}}</td>
    <td>{{accident.update_date}}</td>
    <td>{{accident.ac_area}}</td>
    <td>{{accident.ac_status}}</td> 
    <td>{{accident.writer}}</td>
    </tr>
    {% endfor %}
    </table>
    <a href="{% url 'board:accident_write' %}" class="btn btn-primary" type="button">작성</a>
</div>
<script>
    function redirectToAccidentDetail(accidentId) {
        var url = "/board/accident_detail/" + accidentId;
        window.location.href = url; }
</script>
{% endblock %}
</body>
</html>

web/board/templates/board/apimap.html
<html>
<head>
	<meta charset="utf-8"/>
	<title>Kakao 지도 시작하기</title>
</head>
<body>
	<div id="map" style="width:500px;height:400px;"></div>
	<script type="text/javascript" src="//dapi.kakao.com/v2/maps/sdk.js?appkey=6270100a3347f8ef1ed3f755f9e6842c"></script>
	<script>
		var container = document.getElementById('map');
		var options = {
			center: new kakao.maps.LatLng(33.450701, 126.570667),
			level: 3
		};

		var map = new kakao.maps.Map(container, options);
	</script>
</body>
</html>

web/board/templates/board/employee_regi.html
{% extends 'page.html' %}
<html lang="ko-kr">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Elsafe-Q 직원등록</title>
</head>

<body>
{% block title %}
<h1 id="title">직원등록</h1>
{% endblock title %}

{% block content %}
{% load static %}
<link rel="stylesheet" href="{% static 'register.css' %}">
    <div class="sign_up">
        <div class="input">
            <label class="blockquote" for="mgr_pw">총 직원{{count}}명   </label>
            <form action="" method="POST" enctype="multipart/form-data">
                {% csrf_token %}
                {{ form.as_p }}
                <input class="btn btn-primary" type="submit" value="등록">
            </form>
        </div>

<div class="output">
    {% if employee %}
        이미지 : <img src="{{ employee.img.url }}" alt="Employee Image" style="width:500px; height:400px;"><br> <br>
        회사 : {{ employee.cmp }} <br>
        직책: {{ employee.position }} <br>
        담당구역: {{ employee.work_area }}<br>
    <form method="POST" action="{% url 'board:employee_delete' pk=employee.id %}">
        {% csrf_token %}
        <button type="submit" class="btn btn-danger" onclick="이 글을 삭제하시겠습니까 ?">삭제</button>
        <a href="{% url 'board:employee_update' pk=employee.id %}" class="btn btn-info" type="button">수정</a>
    </form>
    {% else %}
        <p>No data selected.</p>
    {% endif %}
</div>

</div>
<div class="table-container" style="width:100%; height:300px; overflow:auto">
<table class="table table-hover" id="myTable" border="1" cellspacing="0" summary="직원 목록">
    <colgroup>
        <col width="50">
        <col width="80">
        <col width="80">
        <col width="80">
        <col width="100">
    </colgroup>
    <thead>
        <th>회사</th>
        <th>직원명</th>
        <th>직책</th>
        <th>담당구역</th>
        <th>작업일</th>
    </thead>
    <tbody>
        {% if object_list %}
        {% for employee in object_list %}
        <tr class="link-dark" onclick="redirectToEmployeeDetail('{{ employee.id }}')" >
            <td>{{ employee.cmp }}</td>
            <td>{{ employee.emp_name }}</td>
            <td>{{ employee.position }}</td>
            <td>{{ employee.work_area }}</td>
            <td>{{ employee.start_time }} - {{ employee.end_time }}</td>
        </tr>
        {% empty %}
        <tr>
            <td colspan="5">직원정보</td>
        </tr>
        {% endfor %}
        {% endif %}
    </tbody>
</table>
</div>
<script>
    function redirectToEmployeeDetail(employeeId) {
        var url = "/board/employee_detail/" + employeeId;
        window.location.href = url;
    }
</script>
{% endblock %}
</body>
</html>

web/board/templates/board/fieldlog_detail.html
{% extends 'page.html' %}
{% block title %}
<h1 id="title">작업현장일지</h1>
{% endblock title %}

{% block content %}
{% if fieldlog %}
{% load static %}
<link rel="stylesheet" href="{% static 'register.css' %}">
{{user.username}}님 환영합니다. <br>
<div class="sign_up">
<div class="input">
이미지 <img src="{{ fieldlog.img.url }}"  style="width:800px; height:600px;"  alt="fieldlog Image"><br>
</div>
<div class="output">
공사구역 {{fieldlog.fl_area}} <br>
작업내역 {{fieldlog.fl_status}} <br>
생성일 {{fieldlog.create_date}} <br>
일지내용 {{fieldlog.fl_cont}}<br>

{% if request.user == fieldlog.writer %}
<form method="POST" action="{% url 'board:fieldlog_delete' pk=fieldlog.id %}">
  {% csrf_token %}
  <button type="submit" class="btn btn-danger" onclick="return confirm('이 글을 삭제하시겠습니까?')">삭제</button>
</form>
<a href="{% url 'board:fieldlog_update' pk=fieldlog.id %}" class="btn btn-info" type="button">수정</a>
{% endif %}
<a href="{% url 'board:fieldlog_write' %}" class="btn btn-light" type="button">목록</a>

<form method="POST" action="{% url 'board:fieldlog_detail' pk=fieldlog.id %}">
    {% csrf_token %}
    {{ replayForm.as_p }}
    <input class="btn btn-primary" type="submit" value="댓글">
</form>

  {% if fieldlog.replay_set.all %}
    {% for replay in fieldlog.replay_set.all %}
      {{ replay.contents }} {{ replay.writer }}<br>
    {% endfor %}
  {% endif %}
</div>
</div>
{% endif %}
{% endblock %}

web/board/templates/board/log.html
<html lang="ko-kr">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Elsafe-Q 일일기록</title>
</head>
<body>
    
</body>
</html>
{% extends 'page.html' %}

{% block title %}
<h1 id="title">Login/Logout Log</h1>
{% endblock title %}

{% block content %}
<table class="table table-hover" id="myTable" border="1" cellspacing="0" summary="로그기록">
    <colgroup>
        <col width = "50">
        <col width = "50">
        <col width = "30">
        <col width = "50">
        <col width = "300">
    </colgroup>
    <thead>
        <tr>
            <th>관리자</th>
            <th>ID</th>
            <th>직책</th>
            <th>관리기록</th>
            <th>기록시간</th>
        </tr>
    </thead>
    <tbody>
        {% for log in logs %}
        <tr>
            <td>{{ log.login.user.last_name }} {{ log.login.user.first_name }}</td>
            <td>{{ log.login.user.username }}</td>
            <td>{{ log.login.user.position }}</td>
            <td>{{ log.duration }}</td>
            <td>{{ log.login.date }} - {{ log.logout.date }} </td>
        </tr>
        {% empty %}
        <tr>
            <td colspan="6">No login/logout logs found.</td>
        </tr>
        {% endfor %}
    </tbody>
</table>
{% endblock %}
{% load static %}
<link rel="stylesheet" href="{% static 'register.css' %}">

web/board/templates/board/login.html
<html lang="ko-kr">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <!-- CSS only 부트스트랩 -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65" crossorigin="anonymous">
    <!-- JavaScript Bundle with Popper -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-kenU1KFdBIe4zVF0s0G1M5b4hcpxyD9F7jL+jjXkk+Q2h455rYXK/7HAuoJl+0I4" crossorigin="anonymous"></script>
    <title>Elsafe-Q</title>
</head>
<body>
{% load static %}
<link rel="stylesheet" href="{% static 'login.css' %}">
    {% if error %}
    <p style="color: red;">{{ error }}</p>
    {% endif %}

<div class="login">
    <form method="POST">
    {% csrf_token %}
    <h1>Elsafe Q</h1>
    <div class="form-floating mb-3">
    <input class="form-control" type="text" name='username'  placeholder="아이디 입력">
    <label for="username">아이디 </label>
    </div>

    <div class="form-floating">
    <input class="form-control" type="password" name='password' placeholder="비밀번호 입력">
    <label for="password">비밀번호 </label>
    </div>

    <div id ="button">
    <input class="btn btn-primary" type="submit" value="로그인">
    <a href="{% url 'board:signup' %}" class="btn btn-primary" type="button">회원가입</a>
    </div>
</form>
</div>
</body>
</html>

web/board/templates/board/safety_detail.html
{% extends 'page.html' %}

{% block title %}
<h1 id="title">안전점검일지</h1>
{% endblock title %}

{% block content %}
{% if safety %}
{{ user.username }}님 환영합니다. <br>
안전점검구역 {{ safety.scl_area }} <br>
안전상태 {{ safety.scl_status }} <br>
이미지 <img src="{{ safety.img.url }}" alt="Safety Image" style="width:500px; height:400px;"><br>
안전점검내용 {{ safety.scl_cont }}<br>

{% if request.user == safety.writer %}
<form method="POST" action="{% url 'board:safety_delete' pk=safety.id %}">
  {% csrf_token %}
  <button type="submit" class="btn btn-danger" onclick="return confirm('이 글을 삭제하시겠습니까?')">삭제</button>
</form>
<a href="{% url 'board:safety_update' pk=safety.id %}" class="btn btn-info" type="button">수정</a>
{% endif %}
<a href="{% url 'board:safety_list' %}" class="btn btn-light" type="button">목록</a>

<form method="POST" action="{% url 'board:safety_detail' pk=safety.id %}">
  {% csrf_token %}
  {{ replayForm.as_p }}
  <input class="btn btn-primary" type="submit" value="댓글">
</form>

{% if safety.replay_set.all %}
{% for replay in safety.replay_set.all %}
{{ replay.contents }} {{ replay.writer }}<br>
{% endfor %}
{% endif %}

{% endif %}
{% endblock %}

web/board/templates/board/safety_form.html
{% extends 'page.html' %}
{% block title %}
<h1 id="title">안전점검일지</h1>
{% endblock title %}

{% block content %}
    <!-- Your dashboard content goes here -->
{{user.username}}님 환영합니다.
<form action="" method="POST" enctype="multipart/form-data">
{% csrf_token %}
{{ form.as_p }}
<input type="submit" value="등록">
</form>
{% endblock %}

web/board/templates/board/safety_list.html
<html lang="ko-kr">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Elsafty</title>
</head>
<body>
{% extends 'page.html' %}
{% load static %}
<link rel="stylesheet" href="{% static 'list.css' %}">

{% block title %}
<h1 id="title">안전점검일지</h1>
{% endblock title %}

{% block content %}
<nav class="navbar bg-light">
    <div class="container-fluid">
        <div class="solt-1">
            <label class="blockquote" for="mgr_pw">총 사건{{total}}건   </label>
            <label class="lead" for="mgr_pw">   양호 {{count1}}건  </label>
            <label class="lead" for="mgr_pw">   주의 {{count2}}건</label>
            <label class="lead" for="mgr_pw">   심각 {{count2}}건</label>
        </div>

      <form class="d-flex" role="search">
        <input class="form-control me-2" type="search" placeholder="보고자 검색" aria-label="보고자">
        <button class="btn btn-outline-success" type="submit">검색</button>
      </form>
    </div>

</nav>
<div id="output">
    <table class="table table-hover" id="myTable" border="1" cellspacing="0" summary="안전점검일지 목록">
    <colgroup>
        <col width = "200">
        <col width = "200">
        <col width = "80">
        <col width = "50">
    </colgroup>
    <thead>
        <th>생성일</th>
        <th>안전점검구역</th>
        <th>안전상태</th>
        <th>보고자</th>
    </thead>
    {% for safety in safety_list  %}
    <tr class="link-dark" onclick="redirectToSafetyDetail('{{safety.id}}')">
    <td>{{safety.create_date}}</td>
    <td>{{safety.scl_area}}</td>
    <td>{{safety.scl_status}}</td> 
    <td>{{safety.writer}}</td>
    </tr>
    {% endfor %}
    </table>
    <a href="{% url 'board:safety_write' %}" class="btn btn-primary" type="button">작성</a>
</div>

<script>
    function redirectToSafetyDetail(safetyId) {
        var url = "/board/safety_detail/" + safetyId;
        window.location.href = url; }
</script>
{% endblock %}
</body>
</html>

web/board/templates/board/signup.html
<html lang="ko-kr">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <!-- CSS only 부트스트랩 -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65" crossorigin="anonymous">
    <!-- JavaScript Bundle with Popper -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-kenU1KFdBIe4zVF0s0G1M5b4hcpxyD9F7jL+jjXkk+Q2h455rYXK/7HAuoJl+0I4" crossorigin="anonymous"></script>
    <title>Elsafe-Q</title>
</head>
<body>
<h1>회원가입</h1>

<form method="POST">
{% csrf_token %}
<div class="mb-3 row">
    <label class="col-sm-2 col-form-label" for="name">관리자</label>
    <div class="col-sm-10">
    <input type="text" class="form-control" name="last_name" placeholder="성 입력" required>
    <input type="text" class="form-control" name="first_name" placeholder="이름 입력" required>
    </div>

    <label class="col-sm-2 col-form-label" for="position">직책</label>
    <select class="form-select" aria-label="Default select example" name="position"  required>
    <option value="" selected>---------</option>
    <option value="감독">감독</option>
    <option value="관리자">관리자</option>
    <option value="반장">반장</option>
    </select>

    <label class="col-sm-2 col-form-label" for="id_edmil">이메일</label>
    <div class="col-sm-10">
    <input type="email" class="form-control" name="email"  placeholder="이메일 입력"required>
    </div>
    
    <label class="col-sm-2 col-form-label" for="id_username">아이디</label>
    <div class="col-sm-10">
    <input type="text" class="form-control" name="username"  placeholder="아이디 입력"required>
    </div>

    <label class="col-sm-2 col-form-label" for="id_password1">비밀번호</label>
    <div class="col-sm-10">
    <input type="password" class="form-control" name="password1" autocomplete="new-password" placeholder="비밀번호 입력" required>
    </div>

    <label class="col-sm-2 col-form-label" for="id_password2" >비밀번호 확인</label>
    <div class="col-sm-10">
    <input type="password" class="form-control" name="password2" autocomplete="new-password" placeholder="비밀번호 확인" required>
    </div>

    <label class="col-sm-2 col-form-label" for="id_address">상세주소</label>
    <div class="col-sm-10">
    <input type="text" class="form-control" name="address" maxlength="200" placeholder="상세주소 입력" required>
    </div>

    <label class="col-sm-2 col-form-label" for="id_call">전화번호</label>
    <div class="col-sm-10">
    <input type="text" class="form-control" name="call" pattern="[0-9]{2,3}-[0-9]{3,4}-[0-9]{4}"
        maxlength="13" placeholder="전화번호 입력" required>
    </div>
    <div id ="button">
    <input class="btn btn-primary" type="submit" value="관리자등록">
    <a href="{% url 'board:login' %}" class="btn btn-primary" type="button">이전</a>
    </div>
</form>
</body>
</html>